apiVersion: 1
datasources:
  - name: Local Netdata Prometheus
    uid: local-netdata-prometheus
    type: prometheus
    access: proxy
    url: http://127.0.0.1:9090
    isDefault: false
    editable: false
    jsonData:
      httpMethod: POST
