[tools]
lefthook = { version = "2.1.12", postinstall = "lefthook install" }

just = "1.58.0"
gh = "2.100.0"

terraform = "1.9"
shellcheck = "0.11.0"
"pipx:yamllint" = "1.38.0"
"aqua:terraform-linters/tflint" = "0.64.0"
"aqua:betterleaks/betterleaks" = "1.8.1"
"aqua:scaleway/scaleway-cli" = "latest"
